### ISSUE TITLE
0.19 breaks compatibility

### ISSUE THREAD

**Issue by AsaAyers** [webpack/css-loader#158] opened 2015-10-02 16:25 UTC
```
ERROR in ../css/main.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/asa/myProject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/home/asa/myProject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/home/asa/myProject/node_modules/css-loader/lib/processCss.js:174:5)
    at Object.module.exports (/home/asa/myProject/node_modules/css-loader/lib/loader.js:22:2)
 @ ./main.js 8:0-52
```

**Comment by ben-eb** [comment] 2015-10-02 17:16
Duplicate of https://github.com/webpack/css-loader/issues/144.

**Closed** 2015-10-02 17:45 UTC
