### ISSUE TITLE
Using CSS Loader on browser

### ISSUE THREAD

**Issue by khankuan** [webpack/css-loader#204] opened 2015-12-14 04:29 UTC
Hi! Is it possible to use this module on browser side?

**Comment by vramana** [comment] 2015-12-14 13:17
@khankuan I don't think so. css-loader reads the files from file-system to build webpack assests. Can you describe your use case more appropriately??

**Comment by vramana** [comment] 2015-12-14 13:28
@khankuan Hey, apparently css-loader works in browser Look at this https://github.com/webpack/playground. But it's completely outdated.

**Comment by khankuan** [comment] 2015-12-14 15:46
Actually I just wanted to use css modules but it seems like only css-loader has a implementation of it :/

**Comment by vramana** [comment] 2015-12-14 15:53
@khankuan Not sure what you mean. the css-modules is just bunch of post-css plugins. I know for fact that you can run post-css transforms inside a browser. So what you are asking should be doable. You need to put some efforts I think. 

Since the issue is not related to css-loader, may be you can close this issue.

**Closed** 2016-11-17 14:59 UTC
