### ISSUE TITLE
List of all possible [placeholders]?

### ISSUE THREAD

**Issue by wzup** [webpack/css-loader#246] opened 2016-03-15 14:20 UTC
Could you pls provide a list of all possible placeholders? Now we know these. Are there any more?
```
[name]
[local]
[path]
[hash:base64:5]
```

**Comment by developit** [comment] 2016-04-12 15:05
These are also supported:

```
[folder]   (parent dir name)
[ext]  (file extension)
[emoji:XXXX]  (emoji by codepoint)
```

From here: https://github.com/webpack/loader-utils/blob/master/index.js#L234

**Comment by psimyn** [comment] 2016-04-21 04:02
duplicate of https://github.com/webpack/css-loader/issues/226 ?

**Comment by bebraw** [comment] 2016-05-14 05:15
Closing as a duplicate.

**Closed by bebraw** 2016-05-14 05:15 UTC

**Comment by seggev319** [comment] 2018-02-15 10:47
@developit link's broken..

**Comment by jdatskuid** [comment] 2018-08-14 18:40
Updated link: https://github.com/webpack/loader-utils/#interpolatename
