### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by iroy2000** [webpack/css-loader#145] opened 2015-09-24 21:06 UTC
Hi all,

I try to update some of my npm packages, and then I'm having this issues.

```sh
ERROR in ./~/css-loader!./~/sass-loader!./src/style/components/home.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/roy/development/stash/chaas-web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Users/roy/development/stash/chaas-web/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/Users/roy/development/stash/chaas-web/node_modules/css-loader/lib/processCss.js:174:5)
    at Object.module.exports (/Users/roy/development/stash/chaas-web/node_modules/css-loader/lib/loader.js:22:2)
 @ ./src/style/components/home.scss 4:14-127 13:2-17:4 13:2-17:4 14:20-133
```

And the following is my package.json

```sh
  "devDependencies": {
    "assets-webpack-plugin": "2.2.x",
    "babel-jest": "5.3.x",
    "css-loader": "0.19.x",
    "file": "0.2.x",
    "file-loader": "0.8.x",
    "html-webpack-plugin": "1.6.x",
    "image-webpack-loader": "1.6.x",
    "imagemin": "3.2.x",
    "jest-cli": "0.5.x",
    "jsx-loader": "0.13.x",
    "node-sass": "3.3.x",
    "react-hot-loader": "1.3.x",
    "react-proxy-loader": "0.3.x",
    "react-tools": "0.13.x",
    "sass-loader": "2.0.x",
    "style-loader": "0.12.x",
    "webpack": "1.12.x",
    "webpack-dev-server": "1.11.x"
  },
```

And this is my webpack config for the scss

```sh
{ test: /\.scss$/, loader: "style-loader!css-loader!sass-loader" }
```

Anyone have idea and much appreciated, thanks.

**Comment by ben-eb** [comment] 2015-09-24 21:09
Duplicate of https://github.com/webpack/css-loader/issues/144.

**Comment by dev-mraj** [comment] 2015-10-05 15:53
same
+1

**Comment by Aknilam** [comment] 2015-10-06 15:53
+1

**Comment by nazywamsiepawel** [comment] 2015-10-13 20:35
+1

**Comment by Strate** [comment] 2015-10-14 08:20
Is there any quick qorkaround?

**Comment by nazywamsiepawel** [comment] 2015-10-14 08:26
@Strate I got it to work by downgrading css-loader to "^0.18.0"

**Comment by wouter-willems** [comment] 2015-10-15 12:16
+1

**Comment by philihp** [comment] 2015-10-15 19:26
+1

**Comment by changtimwu** [comment] 2015-10-16 01:04
+1 @nazywamsiepawel  .

**Comment by wouter-willems** [comment] 2015-10-16 08:45
@nazywamsiepawel thnx, that did the trick

**Comment by sean-stanley** [comment] 2015-10-19 18:44
I fixed problem by switching to node version 0.12.7 I guess 0.19.0 uses a dependency that breaks on node 0.10?

It's a bit frustrating as my older projects can't use 0.12 so I'll have to switch back to 0.10 when I switch projects.

**Comment by umarashfaq** [comment] 2015-10-23 15:18
Had the same problem. Realized I had Node v0.10.26 (gosh!) installed. [Upgraded to latest stable version](http://davidwalsh.name/upgrade-nodejs) (v4.2.1) and the problem was fixed.

**Comment by andre-gh** [comment] 2015-10-27 18:12
Fyi for anyone who is unable to update for various project constraint reasons, `require('es6-promise').polyfill()` in your webpack config should fix the issue.

**Comment by anilpai** [comment] 2015-10-29 20:24
Thanks @andre-gh .. Works !!

**Comment by yangshun** [comment] 2015-11-08 17:51
I upgraded my node to v0.12.7 and it worked.

**Comment by dr-nafanya** [comment] 2015-11-25 19:43
@andre-gh thanks - the workaround works perfectly!

**Comment by rish1690** [comment] 2015-11-30 03:45
@andre-gh thank you for saving my day

**Comment by jackgeek** [comment] 2015-12-18 13:29
I'm getting this on node v5.3.0

**Comment by Kobold** [comment] 2015-12-25 15:43
@andre-gh Thanks man!

**Comment by keithsun80** [comment] 2015-12-26 14:17
I got this problem on node: '0.10.40'.
To upgrade node version to node: '4.2.4' , solve this problem.

**Comment by yanhaijing** [comment] 2015-12-27 14:05
Had the same problem. Realized I had Node v0.10.29 (gosh!) installed

**Comment by MarcusMann** [comment] 2016-01-06 04:02
I'am I did downgrade of nodejs 0.10 to v5.3.0

on ubuntu:

sudo apt-get remove nodejs

Install nodeJS v5.3.0:
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by yanhaijing** [comment] 2016-01-06 05:29
I can't upgrade，Too many project dependencies

**Comment by FintanK** [comment] 2016-01-07 22:24
@nazywamsiepawel thank you

**Comment by philihp** [comment] 2016-01-07 22:31
@yanhaijing I believe in you! Don't let your dreams be dreams!!

**Comment by markdalgleish** [comment] 2016-01-07 23:42
Closing as this is a duplicate of https://github.com/webpack/css-loader/issues/144, as mentioned already by @ben-eb. He also proposed a solution for those stuck on older versions of Node, by polyfilling `global.Promise`.

**Closed by markdalgleish** 2016-01-07 23:42 UTC

**Comment by yanhaijing** [comment] 2016-01-08 02:12
@philihp thank you

**Comment by dopeboy** [comment] 2016-01-17 04:15
Thanks @nazywamsiepawel - am in the same boat as others where I can't upgrade.

**Comment by scottsword** [comment] 2016-01-29 15:51
Upgrading to node 0.12.x works too, in case you can't make the leap to 4.

**Comment by UndergroundLabs** [comment] 2016-02-24 22:30
Downgrading css-loader worked.

**Comment by jcarva** [comment] 2016-06-22 18:38
Thanks guys, I'm had the same problem. Upgrading to Node v6.2.2 works perfectly !!

**Comment by usirin** [comment] 2016-08-08 08:06
```js
// first line of webpack.config.js
global.Promise = require('bluebird')
```
if you already have `bluebird`.

**Comment by fhurta** [comment] 2016-08-12 08:39
The same problem here, with
node 6.2.1
css-loader 0.23.1

Workaround suggested by @andre-gh 

> require('es6-promise').polyfill() in your webpack config

 works for me too

**Comment by martynchamberlin** [comment] 2016-08-17 21:26
@fhurta Same for me. `npm install es6-promise --save` and then added `require('es6-promise').polyfill()` at the top of `webpack.config.js`.

**Comment by ketabi** [comment] 2018-01-11 12:22
You can use Promise: 'es6-promise' in your webpack config: 
   ```
 plugins: [
        //tells webpack where to store data about your bundles.
        new BundleTracker({filename: './webpack-stats.json'}),

        //makes jQuery available in every module
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            Promise: 'es6-promise'
        }),

        // Configure path for served CSS files ("desktop_css" will be served as /dist/desktop_css.css)
        new ExtractTextPlugin('[name].css'),
    ],
```

https://stackoverflow.com/questions/35769777/axios-ie-promise-doesnt-work/48203092#48203092

I had this in Android 4.x browsers and about using axios And Promise there.
