### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by jack-nie** [webpack/css-loader#179] opened 2015-11-05 16:02 UTC
my entry.js:
         `require('./style.css');`
my webpack file:
```javascript
var webpack = require('webpack');
var htmlWebPackPlugin = require('html-webpack-plugin');
var path = require('path');
var SRC_PATH = path.join(__dirname, 'src');
var TARGET_PATH = path.join(__dirname, 'assets');

module.exports = {
  entry: [
    'webpack-dev-server/client?http://127.0.0.1:8080', 
    'webpack/hot/only-dev-server',
    path.join(SRC_PATH, 'js', 'entry.js')
  ],
  output: {
    path: TARGET_PATH,
    filename: '[name].js',
    publicPath: ''
  },
  module: {
    loaders: [
      { test: /\.css$/, loader: "style-loader!css-loader" },
      { test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" },
      { test: /\.html$/, exclude: /node_modules/, loader: "raw" },
      //{ test: /\.jsx?$/, loaders: ['react-hot', 'jsx?harmony'], exclude: /node_modules/ }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new htmlWebPackPlugin({
      inject: true,
      template: 'src/index.html'
    }),
    new webpack.NoErrorsPlugin()
  ]
};
```
my package.json file:
```
  "devDependencies": {
    "react-hot-loader": "~1.3.0",
    "babel-core": "~5.8.25",
    "babel-loader": "~5.3.2",
    "showdown": "~1.3.0",
    "jquery": "~2.1.4",
    "html-webpack-plugin": "~1.6.2",
    "fs": "0.0.2",
    "style-loader": "~0.13.0",
    "css-loader": "~0.22.0"
  },
  "dependencies": {
    "body-parser": "^1.4.3",
    "express": "^4.4.5",
    "react-dom": "~0.14.1",
    "react": "~0.14.1",
    "showdown": "~1.3.0",
    "jquery": "~2.1.0"
  }
```
here is the error message:
```
ERROR in ./~/css-loader!./src/js/style.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/work/react-demo/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/work/react-demo/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/work/react-demo/node_modules/css-loader/lib/processCss.js:181:5)
    at Object.module.exports (/work/react-demo/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/js/style.css 4:14-79 13:2-17:4 14:20-85
```

**Comment by formula349** [comment] 2015-11-09 15:13
I'm getting the same error after updating to latest version of webpack and related. Any ideas where to start troubleshooting?

**Comment by ben-eb** [comment] 2015-11-09 15:14
Duplicate of https://github.com/webpack/css-loader/issues/144 and https://github.com/webpack/css-loader/issues/145.

**Comment by bebraw** [comment] 2016-01-08 13:36
Closing as duplicate.

**Closed by bebraw** 2016-01-08 13:36 UTC
